# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
     - main

pool:
 name: DGSPool

variables:
  buildConfiguration: 'Release'

jobs:
  - job: 
    steps:
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: "Build"
        inputs:
          command: 'build'
          configuration: $(buildConfiguration)
          projects: '**/*.csproj'
  
      - task: DotNetCoreCLI@2
        displayName: "Running Tests"
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
      
      - task: DotNetCoreCLI@2
        displayName: "Publish App"
        inputs:
          command: 'publish'
          arguments: --output $(Build.ArtifactStagingDirectory)
          publishWebProjects: true

      - task: PublishBuildArtifacts@1
        displayName: "Upload Articfact"
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'dgsn'
          publishLocation: 'Container'